project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: assets/favicon.jpg
  navbar:
    logo: assets/logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      -  href: assets/_cv.pdf
         text: CV
      - projects.qmd
      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true
    page-layout: full



